"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-default-key-for-development')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Configure for both local and production
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# CSRF trusted origins - Dynamic configuration
def get_csrf_trusted_origins():
    """Generate CSRF trusted origins dynamically."""
    origins = []
    
    # Generate port ranges dynamically
    def get_ports():
        ports = []
        # Common development port ranges
        ports.extend(range(3000, 3009))  # 3000-3008 (React dev servers)
        ports.extend([8080, 4200, 5173])  
        return ports
    
    hosts = ['localhost', '127.0.0.1']
    protocols = ['http', 'https']
    
    # Generate combinations
    for host in hosts:
        for port in get_ports():
            for protocol in protocols:
                origins.append(f"{protocol}://{host}:{port}")
    
    # Add custom local origins from environment
    custom_origins = os.environ.get('CSRF_LOCAL_ORIGINS', '').split(',')
    origins.extend([origin.strip() for origin in custom_origins if origin.strip()])
    
    # Add production origins from environment
    prod_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    origins.extend([origin.strip() for origin in prod_origins if origin.strip()])
    
    return origins

CSRF_TRUSTED_ORIGINS = get_csrf_trusted_origins()

# Application definition

INSTALLED_APPS = [
  "django.contrib.admin",
  "django.contrib.auth",
  "django.contrib.contenttypes",
  "django.contrib.sessions",
  "django.contrib.messages",
  "django.contrib.staticfiles",
  "rest_framework",
  "corsheaders",
  "django_filters",
  "files",
]

MIDDLEWARE = [
  "django.middleware.security.SecurityMiddleware",
  "whitenoise.middleware.WhiteNoiseMiddleware",
  "django.contrib.sessions.middleware.SessionMiddleware",
  "corsheaders.middleware.CorsMiddleware",
  "core.middleware.user_id.UserIdMiddleware",
  "core.middleware.rate_limit.RateLimitMiddleware",
  "django.middleware.common.CommonMiddleware",
  "django.middleware.csrf.CsrfViewMiddleware",
  "django.contrib.auth.middleware.AuthenticationMiddleware",
  "django.contrib.messages.middleware.MessageMiddleware",
  "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
  {
    "BACKEND": "django.template.backends.django.DjangoTemplates",
    "DIRS": [],
    "APP_DIRS": True,
    "OPTIONS": {
      "context_processors": [
        "django.template.context_processors.debug",
        "django.template.context_processors.request",
        "django.contrib.auth.context_processors.auth",
        "django.contrib.messages.context_processors.messages",
      ],
    },
  },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
  "default": {
    "ENGINE": "django.db.backends.sqlite3",
    "NAME": os.path.join(BASE_DIR, 'data', 'db.sqlite3'),
  }
}

# Cache configuration for rate limiting
# Use LocMemCache for development/testing, Redis/Memcached for production
# 
# For production with Redis, use:
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         }
#     }
# }
#
# For production with Memcached, use:
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
#         'LOCATION': '127.0.0.1:11211',
#     }
# }
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
  },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework settings (moved to bottom for better organization)

# CORS settings - Environment-aware configuration
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'True') == 'True'  # False in production
CORS_ALLOW_CREDENTIALS = True

# Production CORS origins (when CORS_ALLOW_ALL_ORIGINS is False)
CORS_ALLOWED_ORIGINS = []
PRODUCTION_CORS_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
if PRODUCTION_CORS_ORIGINS and PRODUCTION_CORS_ORIGINS != ['']:
    CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in PRODUCTION_CORS_ORIGINS if origin.strip()])
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'userid',  # Custom header for our API
    'UserId',  # Custom header for our API
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_EXPOSE_HEADERS = [
    'x-user-id',  # Expose UserId in response headers
]
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours
CORS_ALLOW_PRIVATE_NETWORK = True


# Storage Settings
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Rate Limiting - configurable via environment variables
RATE_LIMIT_CALLS = int(os.getenv('MAX_CALLS', '2'))
RATE_LIMIT_WINDOW = int(os.getenv('TIME_WINDOW', '1'))  # seconds

# Storage Quota - configurable via environment variables
STORAGE_QUOTA_PER_USER = int(os.getenv('STORAGE_QUOTA_PER_USER', '10485760'))  # 10MB default

# Pagination
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ]
}
