# Generated by Django 4.2.25 on 2025-10-19 23:30

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorage',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('total_storage_used', models.BigIntegerField(default=0)),
                ('original_storage_used', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Storage',
                'verbose_name_plural': 'User Storage Records',
                'db_table': 'user_storage',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=files.models.file_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('is_reference', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('original_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='files.file')),
            ],
            options={
                'db_table': 'file_uploads',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user_id', 'uploaded_at'], name='file_upload_user_id_061c5a_idx'), models.Index(fields=['user_id', 'file_type'], name='file_upload_user_id_3613f9_idx'), models.Index(fields=['file_hash'], name='file_upload_file_ha_d14f52_idx'), models.Index(fields=['is_reference'], name='file_upload_is_refe_5640f3_idx')],
            },
        ),
    ]
