# Generated by Django 4.2.25 on 2025-10-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='file_upload_file_ha_d14f52_idx',
        ),
        migrations.RenameIndex(
            model_name='file',
            new_name='idx_user_uploaded',
            old_name='file_upload_user_id_061c5a_idx',
        ),
        migrations.RenameIndex(
            model_name='file',
            new_name='idx_user_filetype',
            old_name='file_upload_user_id_3613f9_idx',
        ),
        migrations.RenameIndex(
            model_name='file',
            new_name='idx_is_reference',
            old_name='file_upload_is_refe_5640f3_idx',
        ),
        migrations.AlterField(
            model_name='file',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user_id', 'size'], name='idx_user_size'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_hash', 'is_reference'], name='idx_hash_ref'),
        ),
    ]
