# Generated by Django 4.2.25 on 2025-10-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_optimize_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user_id', 'original_filename'], name='idx_user_filename'),
        ),
    ]
