# Generated by Django 4.2.26 on 2025-11-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_add_filename_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('files', models.ManyToManyField(blank=True, related_name='search_keywords', to='files.file')),
            ],
            options={
                'verbose_name': 'File Search Index',
                'verbose_name_plural': 'File Search Indexes',
                'db_table': 'file_search_index',
                'ordering': ['keyword'],
                'indexes': [models.Index(fields=['keyword'], name='idx_search_keyword')],
            },
        ),
    ]
